apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant1-compute-quota
  namespace: tenantone
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tenant1app
  namespace: tenantone
spec:
  selector:
    app: tenant1app
  type: NodePort
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant1app
  labels:
    app: tenant1app
  namespace: tenantone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tenant1app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tenant1app
    spec:
      containers:
      - image: 682651395775.dkr.ecr.us-east-1.amazonaws.com/tenan-ecrdo-ejizmjpczu6:springapp.master..2019-08-22.02.55.40.ae436947
        imagePullPolicy: Always
        name: tenant1app
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
          limits:
            cpu: 400m
            memory: 1Gi
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: KEYDATA
          value: "ValueData"
      nodeSelector:
          nodegroup-type: tenanttwo-backend-workloads
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tenant1-ingress
  namespace: tenantone
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=14400
  labels:
    app: tenant1-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: tenant1app
              servicePort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tenant1app
  namespace: tenantone
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenant1app
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
